services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    ports:
      - "${PORT:-2283}:2283"
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich-redis
    volumes:
      - ${UPLOAD_LOCATION:-./upload}:/usr/src/app/upload
    depends_on:
      - immich-redis
      - immich-postgres

  immich-redis:
    image: redis:7-alpine
    container_name: immich-redis
    restart: unless-stopped
    volumes:
      - immich-redis-data:/data

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - immich-postgres-data:/var/lib/postgresql/data

volumes:
  immich-redis-data:
  immich-postgres-data:
