services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ha-config:/config

volumes:
  ha-config:
